#!/bin/bash
g="\e[92;1m"
RED="\033[31m"
NC='\033[0m'
y='\033[1;93m'
gg='\e[1;77m'
ungu="\033[0;35m"
clear
echo " "
echo " "
sed -i "d" /var/log/udp.log 
sed -i "d" /tmp/login-udp-db1.txt
journalctl -u udp-custom -n 500 > /var/log/udp.log
cat /var/log/udp.log | grep -i "Client connected" > /tmp/login-udp.txt;
cat /var/log/udp.log | grep -i "Client disconnected" | awk '{print $14}' | cut -d ":" -f 2 > /tmp/login-udp1.txt;
data=(`cat /tmp/login-udp.txt | awk '{print $9}' | cut -d ":" -f 3 | cut -d "]" -f 1`)
for akun in "${data[@]}"
do
            cat /tmp/login-udp.txt | grep -wE "$akun" | awk '{print $9" "$10}'> /tmp/login-udp-db.txt;
            IP=`cat /tmp/login-udp-db.txt | awk '{print $1}' | cut -d ":" -f 2`;
            USER=`cat /tmp/login-udp-db.txt | awk '{print $2}' | cut -d ":" -f 2 | cut -d "]" -f 1`;
                    echo "$USER $IP"  >> /tmp/login-udp-db1.txt;
done
sed -i '/^[[:digit:]]/d' /tmp/login-udp-db1.txt
sed -i '/[[:digit:]]$/!d' /tmp/login-udp-db1.txtt
sed -i "d" /tmp/login-udp-fix.txt
cat /tmp/login-udp-db1.txt | sort | uniq > /tmp/login-udp-fix.txt
clear
data3=(`cat /tmp/login-udp-fix.txt | awk '{print $2}'`)
echo -e "  ${y}───────────────────────────────────────${NC}"
echo -e "            ️ ${g}USER LOGIN UDP${NC}  ️"
echo -e "  ${y}───────────────────────────────────────${NC}"
echo -e "\033[1;36m┌──────────────────────────────────────────┐\033[0m"
for akun in "${data3[@]}"
do
ipon=$(cat /tmp/login-udp.txt | grep -wE "$akun" | wc -l)
ipof=$(cat /tmp/login-udp1.txt | grep -wE "$akun" | wc -l)
let jum=(${ipon}-${ipof})
if [[ $jum -gt "0" ]]; then
 USER=`cat /tmp/login-udp-fix.txt | grep -wE "$akun" | awk '{print $1}' | uniq`;
 IP=`cat /tmp/login-udp-fix.txt | grep -wE "$akun" | awk '{print $2}' | uniq`;
printf "  %-13s %-7s %-8s %2s\n"  "Aktif   $USER   $IP"
else
echo -ne
fi
done
echo -e "\033[1;36m└──────────────────────────────────────────┘\033[0m"

