#!/bin/bash


#install
apt update && apt upgrade
apt install neofetch -y
apt install python3 python3-pip git
clear
neofetch
echo -e "  \e[92;1m Information System \e[0m"
echo -e "  \e[97;1m---------------------------------------${NC}"
echo -e "  \e[97;1m            TUNNELING OFFICIAL             ${NC}"
echo -e "  \e[97;1m---------------------------------------${NC}"
echo -e ""
