#!/bin/bash
REDBLD="\033[0m\033[91;1m"
Green="\e[92;1m"
RED="\033[1;31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
z="\033[1;96m"
NC='\e[0m'
######################################
MYIP=$(curl -sS ipv4.icanhazip.com)
######################################
#IPVPS=$(curl -s ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
RAM=$(free -m | awk 'NR==2 {print $2}')
MODEL=$(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')

#uptime="$(uptime -p | cut -d " " -f 2-10)"
#cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
#cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
#cpu_usage+=" %"

clear
# // Gettings Info
######################################
# // USERNAME IZIN IPP
rm -f /usr/bin/user
username=$(curl -sS https://raw.githubusercontent.com/arivpnstores/izin/main/ip | grep $MYIP | awk '{print $2}')
echo "$username" >/usr/bin/user
rm -f /usr/bin/e
valid=$(curl -sS https://raw.githubusercontent.com/arivpnstores/izin/main/ip | grep $MYIP | awk '{print $3}')
echo "$valid" > /usr/bin/e

clear
######################################
# // DETAIL ORDER IZIN IP
#username=$(cat /usr/bin/user)
oid=$(cat /usr/bin/ver)
exp=$(cat /usr/bin/e)
######################################
clear
# // DAYS LEFT
d1=$(date -d "$valid" +%s)
d2=$(date -d "$today" +%s)
certifacate=$(((d1 - d2) / 86400))
if [[ $certifacate -le 0 ]]; then
masaaktif="EXPAIRED"
else
masaaktif="${certifacate} Day"
fi
clear
######################################
# // GETTINGS SYSTEM
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

clear
######################################
# // RUNNING SSH
######################################
if [[ $ssh_service == "running" ]]; then 
   status_ssh="\033[92;1mON${NC}"
else
   status_ssh="\033[91;1mOFF${NC} "
fi
######################################
# // RUNNING WEBSOCKET
######################################
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="\033[92;1mON${NC}"
else
    status_ws_epro="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING HAPROXY
######################################
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="\033[92;1mON${NC}"
else
   status_haproxy="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING XRAY
######################################
if [[ $xray_service == "running" ]]; then 
   status_xray="\033[92;1mON${NC}"
else
   status_xray="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING NGINX
######################################
if [[ $nginx_service == "running" ]]; then 
   status_nginx="\033[92;1mON${NC}"
else
   status_nginx="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING DROPBEAR
######################################
if [[ $dropbear_service == "running" ]]; then 
   status_dropbear="\033[92;1mGOOD${NC}"
else
   status_dropbear="\033[91;1mCRAZY${NC} "
fi

# \\ Vless account //
vlx=$(grep -c -E "^#& " "/etc/xray/config.json")
let vla=$vlx/2
# \\ Vmess account //
vmc=$(grep -c -E "^### " "/etc/xray/config.json")
let vma=$vmc/2
# \\ Trojan account //
ssh1="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
trx=$(grep -c -E "^#! " "/etc/xray/config.json")
let trb=$trx/2
# \\ shadowsocks account //
ssx=$(grep -c -E "^#!# " "/etc/xray/config.json")
let ssa=$ssx/2

kemarin=$(date -d "-1 days" +"%m-%d")
hariini=$(date -d "0 days" +"%m-%d")
kemarin1=$(date -d "-1 days" +"%m/%d")
hariini1=$(date -d "0 days" +"%m/%d")
bulan=$(date +"%b '%y")
bulan1=$(date +"%Y-%m")
kemarin2=$(vnstat -d | grep -w "${kemarin}" | awk '{print $8" "substr ($9 ,1 ,1) substr ($9 ,3 ,1)}') 
kemarin3=$(vnstat -d | grep -w "${kemarin1}" | awk '{print $8" "substr ($9 ,1 ,1) substr ($9 ,3 ,1)}') 
if [[ $kemarin2 == "" ]]; then
bwkmrn=${kemarin3}
else
bwkmrn=${kemarin2}
fi
if [[ $bwkmrn == "" ]]; then
bwkmrn1="NEWVPS "
else
bwkmrn1=${bwkmrn}
fi
hariini2=$(vnstat -d | grep -w "${hariini}" | awk '{print $8" "substr ($9 ,1 ,1) substr ($9 ,3 ,1)}') 
hariini3=$(vnstat -d | grep -w "${hariini1}" | awk '{print $8" "substr ($9 ,1 ,1) substr ($9 ,3 ,1)}') 
if [[ $hariini2 == "" ]]; then
bwhari=${hariini3}
else
bwhari=${hariini2}
fi
bulan2=$(vnstat -m | grep -w "${bulan}" | awk '{print $9" "substr ($10 ,1 ,1) substr ($10 ,3 ,1)}') 
bulan3=$(vnstat -m | grep -w "${bulan1}" | awk '{print $8" "substr ($9 ,1 ,1) substr ($9 ,3 ,1)}') 
if [[ $bulan2 == "" ]]; then
bwbln=${bulan3}
else
bwbln=${bulan2}
fi

function rif_Banner() {
clear
echo -e "\e[1;96m┌─────────────────────────────────────────────────┐\e[0m"
echo -e "\e[1;96m│ \e[41;1m                ARISCTUNNEL V4                 \e[0m \e[1;96m│\e[0m"
echo -e "\e[1;96m└─────────────────────────────────────────────────┘\e[0m"
}

function Service_System_Operating() {
echo -e "${z}┌─────────────────────────────────────────────────┐\033[0m "
echo -e "${z}│${NC} SYSTEM          : $(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')     \033[0m "
echo -e "${z}│${NC} RAM             : $(free -m | awk 'NR==2 {print $2}')    \033[0m "
echo -e "${z}│${NC} UPTIME          : $(uptime -p | cut -d " " -f 2-10)\033[0m "
echo -e "${z}│${NC} IP VPS          : $(curl -s ipv4.icanhazip.com)     \033[0m "
echo -e "${z}│${NC} CITY            : $(cat /etc/xray/city)    \033[0m "
echo -e "${z}│${NC} ISP             : $(cat /etc/xray/isp)    \033[0m "
echo -e "${z}│${NC} DOMAIN          : $(cat /etc/xray/domain)    \033[0m "
echo -e "${z}└─────────────────────────────────────────────────┘\033[0m"
}

function Service_Status() {
echo -e "\033[96;1m┌─────────────────────────────────────────────────┐\033[0m "
echo -e "\033[96;1m|\e[0m PROXY :\e[0m $status_haproxy \e[96;1m|\e[0m \e[0m NGINX :\e[0m $status_nginx \e[96;1m|\e[0m \e[0m XRAY :\e[0m $status_xray \e[0m| $status_dropbear  \e[96;1m  | \e[0m "
echo -e "\033[96;1m└─────────────────────────────────────────────────┘\033[0m "
}

function List_All_Account() {
echo -e "${z}     ┌───────────────────────────────────────┐\033[0m "
echo -e "              SSH OPENVPN    :     $ssh1         \033[0m " 
echo -e "              VLESS XRAY     :     $vla          \033[0m " 
echo -e "              VMESS XRAY     :     $vma          \033[0m " 
echo -e "              TRJAN XRAY     :     $trb          \033[0m " 
echo -e "              SSR-LIBEV      :     $ssa          \033[0m "   
echo -e "${z}     └───────────────────────────────────────┘\033[0m "
}

function Details_Clients_Name() {
echo -e "${z}   ┌───────────────────────────────────────────┐\033[0m "
echo -e "${z}   │\e[97m  VERSION     : ${BLUE}4.0 LTS \033[0m "
echo -e "${z}   │\e[97m  CLIENTS     :\033[0m\033[92;1m $(cat /usr/bin/user)   \033[0m "
echo -e "${z}   │\e[97m  Expiry In   :\033[0m\033[92;1m $masaaktif  \033[0m "
echo -e "${z}   └───────────────────────────────────────────┘\033[0m "
}

function Details_Bw_Clients() {
echo -e "${z}   ┌───────────────────────────────────────────┐\033[0m "
echo -e "${z}   │${NC} KEMARIN   |   HARI INI   |   BULANAN     \033[0m "
echo -e "${z}   │${NC}\033[91;1m ${bwkmrn1}     ${bwhari}      ${bwbln}\033[0m "
echo -e "${z}   └───────────────────────────────────────────┘\033[0m "
}

function Acces_Use_Command() {
echo -e "${z} —————————————————————————————————————————————————${NC}"
echo -e "${z}           acces use \033[93;1m☞ \033[92;1mmenu ${z} command ${NC} " 
echo -e "${z} —————————————————————————————————————————————————${NC}"
}



rif_Banner
Service_System_Operating
Service_Status
List_All_Account
Details_Clients_Name
Details_Bw_Clients
Acces_Use_Command
